
image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - unset CI
    - BASE_PATH=62df582a4d40d90014e0c7c5/ npm run build
    - mv public public2
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
  